### ISSUE TITLE
Couple of typos

### ISSUE THREAD

**Issue by antithalian** [amitmerchant1990/how-products-got-their-name#12]
I really enjoyed reading this list, so thanks for putting it together!

While I was reading I noticed a couple of small typos and the like. Would you have a problem with me making a pull request to fix the ones I noticed? In addition, I think I know of a few pieces of software that I could add to the list with sources on their naming.

**Comment by amitmerchant1990** [comment]
Yes sir! You can go ahead. Just make sure you follow the existing pattern.

**Comment by antithalian** [comment]
Awesome! I'll get a PR in sometime soon.
