### ISSUE TITLE
MariaDB

### ISSUE THREAD

**Issue by letharion** [amitmerchant1990/how-products-got-their-name#6]
Following MySQL is of course MariaDB, named after Montys younger daughter: https://mariadb.com/kb/en/library/why-is-the-software-called-mariadb/

**Comment by hobofan** [comment]
~\+ [MaxDB](https://en.wikipedia.org/wiki/MaxDB) named after his son.~

Looking into it there doesn't actually seem to be a reputable source for that ~and no proof of any association to MaxDB~.

> Development was done by SAP AG, MySQL AB

Okay, there seems to be some association but still no official confirmation for it 🙄 😄
