### ISSUE TITLE
Operating system, not operation system

### ISSUE THREAD

**Issue by mattl** [amitmerchant1990/how-products-got-their-name#7]
Small typo on the Ubuntu and Debian entries.

And here's one for the GNU operating system: 

> The name “GNU” was chosen because it met a few requirements; first, it was a recursive acronym for “GNU's Not Unix”, second, because it was a real word, and third, it was fun to say (or Sing) [[1]](https://www.gnu.org/gnu/gnu-history.html)

**Comment by amitmerchant1990** [comment]
Fixed it here: https://github.com/amitmerchant1990/how-products-got-their-name/commit/7618231300f65cb3dee54d924f7b65795301267a

**Comment by amitmerchant1990** [comment]
I'll add GNU later. Thanks!
